### PR TITLE
Make Block.merkilize_transaction_set a function

### LINKED ISSUE #101: Block.merkilize_transaction_set should not be a property
[Block](https://github.com/omisego/plasma-mvp/blob/master/plasma/child_chain/block.py) currently specifies `merkilize_transaction_set` as a property, but it should probably be a function:

```
    @property
    def merkilize_transaction_set(self):
        hashed_transaction_set = [transaction.merkle_hash for transaction in self.transaction_set]
        self.merkle = FixedMerkle(16, hashed_transaction_set, hashed=True)
        return self.merkle.root
```

### PR DESCRIPTION
**Pull request by nvonpentz**
Resolves #101 

Please let me know if I should add tests.

Minor, I also noticed 'merkel' is spelled 'merkle' or 'merkil' throughout.

### CODE REVIEW

**Comment by kfichter** [comment]
Thank you for this PR! Much appreciated. 

> Minor, I also noticed 'merkel' is spelled 'merkle' or 'merkil' throughout

It's correctly "Merkle," but `merkilize` is definitely wrong. Can we go ahead and refactor this to `merklize`? Seems to be the prevailing spelling.

**Comment by kfichter** [comment]
Otherwise, LGTM :+1: signing off on this.

**Comment by nvonpentz** [comment]
> It's correctly "Merkle," but merkilize is definitely wrong. Can we go ahead and refactor this to merklize? Seems to be the prevailing spelling.

You're right, changing now.

**Comment by DavidKnott** [comment]
LGTM, @nvonpentz mind rebasing?

**Comment by nvonpentz** [comment]
@DavidKnott Rebased 👍

**Pull request merged**
