### PR TITLE
Fix quotes in Makefile

### PR DESCRIPTION
**Pull request by dschaller**

### CODE REVIEW

**Comment by dschaller** [comment]
@DavidKnott small one for you :D

**Comment by stevenspasbo** [comment]
That description is incomplete, it should be updated to something like "Deploys the root chain contract"

**Comment by dschaller** [comment]
Yeah, this is just a bug fix

**Comment by DavidKnott** [comment]
LGTM

**Comment by dschaller** [comment]
@DavidKnott can this be merged?

**Pull request closed without merging**
