### PR TITLE
Solution to Issue #161 - Many Failing Test Cases

### PR DESCRIPTION
**Pull request by bh2smith**
Quick fix to recover passing test cases mentioned in [#161](https://github.com/omisego/plasma-mvp/issues/161)

Also, added one line to .gitignore (for PyCharm IDE)

### CODE REVIEW

**Comment by bh2smith** [comment]
Notice that the above change also repairs the _sendtx_  OMG command.

**Comment by PaulRBerg** [comment]
You could add the `.idea` folder in your [global gitignore](https://stackoverflow.com/questions/12254076/how-do-i-show-my-global-git-config).

**Comment by PaulRBerg** [comment]
On OSX and python 3.6, I get the same number of failing tests, 11, that is, on both the main repo and your fork.

**Comment by bh2smith** [comment]
@PaulRBerg; You're comments lead me to believe you aren't up to date with the most recent commits. 
```
checkout 04df88122689b5e050e9e11da39b3c8ede02e157
```

**Comment by PaulRBerg** [comment]
I simply cloned the repo and run `make test` right away, thus I should've had the latest version.

`04df88122689b5e050e9e11da39b3c8ede02e157` seems to be 4 commits behind the latest one, so I'm not entirely sure what you're referring to.

I ran it anyway on that commit but I still got the same number of errors.

**Comment by bh2smith** [comment]
I just mentioned because that is where .idea had already been included in the .gitignore.
Couldn't say where the errors are coming from, because I am experiencing no difficulties. I have been working in a different branch (dev) lately and merged it to my master just now in case this is where the errors were coming from.

**Comment by bh2smith** [comment]
@PaulRBerg Maybe you could provide more details about your failing tests. Perhaps the error messages? I suspect that cloning a repo and running `make test` could lead to some issues with dependencies.

**Pull request closed without merging**
