### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by kfichter**
Syncs the README with the latest CLI update.

### CODE REVIEW

**Comment by eashend** [comment]
A quick nit,
on line 241 for the demo, the omg preceding the withdrawdeposit command is missing.

**Comment by kfichter** [comment]
Good catch. Thanks! Changing in a second.

**Comment by rcallan** [comment]
hey, another small thing. I think the withdraw command example should be modified a bit so that it refers to the right block number. maybe
```
omg withdraw 1000 0 0 3bb369fecdc16b93b99514d8ed9c2e87c5824cf4a6a98d2e8e91b7dd0c063304
```
you could also add something like that for the CLI example section

**Comment by kfichter** [comment]
@rcallan Good catch, updated.

**Pull request merged**
