### PR TITLE
started adding some error handling for child chain service

### LINKED ISSUE #99: Improve ChildChainService error handling
Errors are not handled in `ChildChainService`. An invalid request will simply result in the following `KeyError`:

```
KeyError: 'result'
```

This error occurs because `ChildChainService` expects each response to have a 'result' field:

```
    def send_request(self, method, args):
        payload = {
            "method": method,
            "params": args,
            "jsonrpc": "2.0",
            "id": 0,
        }
        response = requests.post(self.url, json=payload).json()
        return response["result"]
```

We should handle this gracefully, perhaps by passing the error back through the server and into the child chain service.

### PR DESCRIPTION
**Pull request by rcallan**
this should fix #99. the invalid requests no longer returns a `KeyError`, and instead passes the error back to the CLI. please feel free to let me know if you have any comments or questions

### CODE REVIEW

**Comment by kfichter** [comment]
Awesome, thanks for the PR! I think we should add the error handling check to each call the CLI makes to the client. Might be easier with a lambda?

```
def client_call(fn, args=()):
    try:
        fn(*args)
    except ChildChainServiceError as err:
        ...
```

and then

```
client_call(client.apply_transaction, args=(tx))
```

Not sure if that ends up being cleaner or more confusing than try/except on each... Need to think about it

**Comment by rcallan** [comment]
a helper function seems like a good way to go. I added one similar to what you mentioned, and so far it's just being used for the client calls that call the child chain service

**Comment by kfichter** [comment]
Awesome, LGTM. Approving.

**Comment by DavidKnott** [comment]
@rcallan Would you mind rebasing?

**Comment by rcallan** [comment]
okay sure, I just did a rebase

**Comment by kfichter** [comment]
Merged, thanks!

**Pull request merged**
